version: '3.7'

services:
  github-runner:
    build:
      context: .
      args:
        - RUNNER_TOKEN=${RUNNER_TOKEN}
    container_name: github-runner
    restart: always
    environment:
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_ALLOW_RUNASROOT=true
