name: Simple CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  echo_hello:
    name: Echo Hello
    runs-on: alphine-container
    environment:
      name: development

    steps:
      - name: Echo Hello
        run: echo "Hello from the 'echo_hello' job"

  echo_world:
    name: Echo World
    runs-on: alphine-container
    environment:
      name: development

    steps:
      - name: Echo World
        run: echo "World from the 'echo_world' job"
      - name: Echo World2
        run: echo "World from the 'echo_world2' job"
      - name: Echo World3
        run: echo "World from the 'echo_world3' job"
      - name: Echo World4
        run: echo "World from the 'echo_world4' job"
  echo_world2:
    name: Echo World2
    needs: [echo_world]
    runs-on: alphine-container
    environment:
      name: development

    steps:
      - name: Echo World
        run: echo "World from the 'echo_world' job"
      - name: Echo World2
        run: echo "World from the 'echo_world2' job"
      - name: Echo World3
        run: echo "World from the 'echo_world3' job"
      - name: Echo World4
        run: echo "World from the 'echo_world4' job"
